# Ubuntu (xenial) as operating system
dist: xenial

# Setup rust environment with stable language branch only
language: rust
rust: stable

# Cache build dependencies
cache: cargo

# System dependency
addons:
  apt:
    packages:
      - inkscape

# Execute build
script: cargo build --verbose

# Deploy build to release platform
deploy:
  provider: pages # Github Pages
  github-token: $GITHUB_TOKEN # Access token for deploy target
  skip-cleanup: true  # Don't clean away output for deploy
  local-dir: "target/book" # Directory to push to Github repository
  repo: "substation-beta/substation-beta.github.io"  # Target repository
  target-branch: "master" # Branch of target repository