# See <https://rust-lang-nursery.github.io/mdBook/format/config.html>

[book]
title = "Substation Beta format"
authors = ["Bastian 'McWhite' Ganze", "Christoph 'Youka' Spanknebel"]
description = "Documentation of Substation Beta format."

[build]
build-dir = "target/book"
create-missing = false

[output.html]
theme = "src/theme"
additional-js = ["assets/customjs/ssb.highlight.min.js"]
