name: Build

on: [push]

jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: substation-beta/ssb_highlight_js_extension
        ref: master
        token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
    - uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn run build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: highlight-build
        path: dist
     
  build:
    needs: [build-deps]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache debug folder
      uses: actions/cache@v1
      with:
        path: target/debug
        key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
    - name: Download deps
      uses: actions/download-artifact@v1
      with:
        name: highlight-build
        path: artifacts/highlight-build
    - name: Move highlight.js to correct folder
      run: mv artifacts/highlight-build/ssb.highlight.min.js assets/customjs/ssb.highlight.min.js
    - name: Build
      run: cargo build --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ssb-book-build-ready
        path: target/book

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: ssb-book-build-ready
          path: artifacts/ssb-book-build-ready
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.2.0
        with:
          personal_token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
          publish_branch: master
          publish_dir: artifacts/ssb-book-build-ready
          external_repository: substation-beta/substation-beta.github.io
